### ISSUE TITLE
How to get list of all header keywords?

### ISSUE THREAD

**Issue by art-den** [simonrw/rust-fitsio#168]
I don't find this option in rust-fitsio API

**Comment by cjordan** [comment]
That's because there is no API for this in `cfitsio`. I have a hacky way of doing this: https://gist.github.com/cjordan/d8ca8a0c1e73be5123e90b4000abf772

**Comment by cjordan** [comment]
Right, well that is an example, not part of the API.  You could write this yourself in Rust using `fitsio-sys`; it would look somewhat like my code above.
