### ISSUE TITLE
Nasa files can't be read

### ISSUE THREAD

**Issue by rafaeling** [simonrw/rust-fitsio#193]
Hi,

could you please look at why NASA files cannot be read using the function? image_data is contains only 0

    let filename = "./testdata/UITfuv2582gc.fits";
    let mut fptr = fitsio::FitsFile::open(filename).unwrap();
    fptr.pretty_print();

    let hdu = fptr.hdu(0).unwrap();

    let image_data: Vec<f32> = hdu.read_image(&mut fptr, ).unwrap();

Data:
https://fits.gsfc.nasa.gov/samples/UITfuv2582gc.fits

**Comment by rafaeling** [comment]
Hi @cjordan thanks for your fast asnwer, however I forgot to say that I used windows and C++ Visual Studio 16 2019 compiler to generate the cfitsio-4.2.0 binaries, I am assuming you are using Ubuntu and a different C++ compiler, am I wrong?

I don't get any error message, only that the image_data vector is completely full of zeros for that file when I debbug it

Regards.

**Comment by cjordan** [comment]
I see. Well `image_data` contains lots of small values for me (order 1e-16). And I'm running Arch linux, although I can't remember if I'm using the repo version of `cfitsio` or my own custom one. `cfitsio` is actually C library, but I guess a C++ compiler could still build it. One thing you could try is using the `fitsio-src` feature, i.e. `cargo run --features fitsio-src`; that will build `cfitsio` from source and link it automatically, so you don't need to have `cfitsio` ahead of time. But, I have no idea if it will work in Windows, only Linux and MacOS.

**Comment by simonrw** [comment]
Thanks for raising this issue. Unfortunately MSVC is not well supported at the moment (poor excuse I know, sorry). You may have more luck with `msys2` or WSL.

As far as the missing data goes, have you tried reading in as `f64` instead, or another data type to see what happens? I remember having similar issues with "raw" `cfitsio` in the past...

**Comment by simonrw** [comment]
It looks to me like there is data, but as @cjordan says it's at a very low level. When I load the image up in ds9 I get a starfield.

<img width="953" alt="image" src="https://user-images.githubusercontent.com/59756/204392643-41167571-1a0b-43e6-9f91-3da6bd9edba2.png">

Would it perhaps look like zeros when you print the first few elements. What do you get if you print element 143114 of the vector (0-indexed)? I get `4.2183192e-13`, which is the largest scale value in the image.

There are some headers that imply scaling is going on, e.g. `CAMSCALE` - perhaps the pixel data are scaled by some constant factors?

Note: the Rust `fitsio` crate (this project) doesn't yet do anything specific with the `BSCALE` and `BZERO` headers, but I think the C `cfitsio` library handles this automatically for us.

**Comment by art-den** [comment]
Tested [UITfuv2582gc.fits](https://fits.gsfc.nasa.gov/samples/UITfuv2582gc.fits) file with `msys2`-version of rust-fitsio under windows. It works. Image is visible but very dark

**Comment by simonrw** [comment]
@rafaeling have you made any progress with this issue?

**Comment by simonrw** [comment]
@rafaeling I'm going to close this issue now. Thanks for reporting it but I can't see anything wrong with `fitsio` on POSIX platforms, and we've checked windows msys2. What support there is for msvc is if anything a coincidence right now unfortunately. I don't have a way of confirming it myself, sorry. If the problem persists, please feel free to re-open the issue and continue this conversation.

I hope that otherwise this crate is suiting your needs. Please don't hesitate to raise any other issues you find!

**Comment by rafaeling** [comment]
Hi @cjordan & @simonrw sorry, I was on vacation till yesterday.

Using a different compiler solved the problem, thanks for such a fast and detail feedback :)

Regards!

**Comment by simonrw** [comment]
Great, glad you could get it resolved. Thanks for using this crate, the more people using it the better it will get. Please feel free to open more issues as and when you find them!
